name: flutter_auth_ui
description: A Flutter plugin for using the Firebase Auth UI with Dart in Flutter apps.
version: 0.2.2
homepage: https://github.com/koji-1009/flutter_auth_ui

flutter:
  plugin:
    platforms:
      android:
        package: com.dr1009.app.flutter_auth_ui
        pluginClass: FlutterAuthUiPlugin
      ios:
        pluginClass: SwiftFlutterAuthUiPlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.0
  flutter_plugin_android_lifecycle: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.9.1 <3.0.0"
  flutter: ">=1.20.2 <2.0.0"
