name: flutter_auth_ui_web
description: Unofficial firebaseui package for flutter. This library aims to provide support for Android, iOS and the web. Login with Email, Phone, Google account and etc.
version: 1.0.2
homepage: https://github.com/koji-1009/flutter_auth_ui/flutter_auth_ui_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterAuthUiWeb
        fileName: flutter_auth_ui_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^9.0.1
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
