name: flutter_auth_ui
description: Unofficial firebaseui package for flutter. This library is personally managed and aims to provide support for Android, iOS and the web. Login with Email, Phone, Apple, Google, GitHub account and etc.
version: 1.2.2
homepage: https://github.com/koji-1009/flutter_auth_ui

flutter:
  plugin:
    platforms:
      android:
        package: com.dr1009.app.flutter_auth_ui
        pluginClass: FlutterAuthUiPlugin
      ios:
        pluginClass: SwiftFlutterAuthUiPlugin
#      web:
#        default_package: flutter_auth_ui_web

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.20.0+1
  flutter_plugin_android_lifecycle: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"
