name: flutter_auth_ui_web_example
description: Demonstrates how to use the flutter_auth_ui_web plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_auth_ui:
    path: ../../flutter_auth_ui/

dependency_overrides:
  flutter_auth_ui_web:
    path: ../

flutter:
  uses-material-design: true
